#!/usr/bin/env node
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import http from 'node:http';
import WebSocket, { WebSocketServer } from 'ws';

import { requireCoordinator } from './relay-lib.mjs';

const statePath = process.env.CRAYS_TEST_ROOM_STATE || '/tmp/crays-manual-test-room.json';
const pidPath = process.env.CRAYS_TEST_ROOM_PID || '/tmp/crays-manual-test-room.pid';
const proxyPort = Number(process.env.CRAYS_TEST_ROOM_PROXY_PORT || 8787);
const proxyEnabled = process.env.CRAYS_TEST_ROOM_PROXY === '1';
const publishOnly = process.env.CRAYS_TEST_ROOM_PUBLISH === '1';
const roomId = process.env.CRAYS_TEST_ROOM_ID || 'crays-test-room';
const roomName = process.env.CRAYS_TEST_ROOM_NAME || 'Crays Test Room';
const scriptEnv = {
  ...process.env,
  CRAYS_QA_STATE: statePath,
  CRAYS_TEST_ROOM_ID: roomId,
  CRAYS_TEST_ROOM_NAME: roomName,
  CRAYS_TEST_ROOM_DOMAIN: `craysdev-room-${Date.now().toString(36)}`,
  CRAYS_TEST_ROOM_TTL_SECONDS: process.env.CRAYS_TEST_ROOM_TTL_SECONDS || '7776000',
  CRAYS_INVITE_TTL_SECONDS: process.env.CRAYS_INVITE_TTL_SECONDS || '7776000',
  // The broadcast credential expires; redeemed test membership intentionally does not.
  CRAYS_BADGE_TTL_SECONDS: process.env.CRAYS_BADGE_TTL_SECONDS || '0',
  CRAYS_INVITE_MAX_REDEMPTIONS: process.env.CRAYS_INVITE_MAX_REDEMPTIONS || String(Number.MAX_SAFE_INTEGER),
  CRAYS_QA_PREAUTHORIZE: process.env.CRAYS_QA_PREAUTHORIZE || '0',
  CRAYS_QA_MINT_INVITE: process.env.CRAYS_QA_MINT_INVITE || '1',
  // Test Room members can publish profile/feed data and anchor-bound NIP-53
  // presence through the same production relay gate as the TestFlight app.
  CRAYS_TEST_ROOM_PRESENCE: '1',
};

let relayCreated = false;
let stopping = false;
let server;
let sockets;
let keepAlive;

function wireCloseCode(code) {
  // RFC 6455 reserves 1005/1006/1015 for local reporting; ws correctly
  // refuses to put them on the wire. Normalize any non-sendable upstream
  // status instead of crashing the relay-only QA proxy.
  return Number.isInteger(code) && code >= 1000 && code <= 4999 && ![1004, 1005, 1006, 1015].includes(code)
    ? code
    : 1011;
}

function runScript(file, env = scriptEnv) {
  execFileSync(process.execPath, [file], { cwd: process.cwd(), env, stdio: 'inherit' });
}

function teardown() {
  if (!relayCreated && !existsSync(statePath)) return true;
  try {
    runScript('.qa/relay-teardown.mjs');
  } catch (error) {
    console.error(`Test room teardown warning: ${error.message}`);
    return false;
  }
  relayCreated = false;
  return true;
}

async function stop(signal, exitCode = 0) {
  if (stopping) return;
  stopping = true;
  console.log(`\nStopping Crays Test Room (${signal})…`);
  for (const socket of sockets?.clients || []) socket.terminate();
  await new Promise((resolve) => server?.close(resolve) || resolve());
  if (keepAlive) clearInterval(keepAlive);
  const clean = teardown();
  rmSync(pidPath, { force: true });
  process.exit(clean ? exitCode : 1);
}

try {
  if (proxyEnabled && (!Number.isInteger(proxyPort) || proxyPort < 1024 || proxyPort > 65535)) throw new Error('CRAYS_TEST_ROOM_PROXY_PORT must be a valid non-privileged port');
  if (existsSync(pidPath)) {
    const previousPid = Number(readFileSync(pidPath, 'utf8').trim());
    try {
      process.kill(previousPid, 0);
      throw new Error(`Crays Test Room is already running as process ${previousPid}`);
    } catch (error) {
      if (error.code !== 'ESRCH') throw error;
      rmSync(pidPath, { force: true });
    }
  }
  await requireCoordinator();
  if (existsSync(statePath)) {
    console.log('Sweeping previous Test Room fixtures from the reserved relay…');
    if (!teardown()) throw new Error('previous reserved-relay fixture cleanup failed');
  }
  runScript('.qa/relay-bootstrap.mjs');
  relayCreated = true;
  const state = JSON.parse(readFileSync(statePath, 'utf8'));

  if (publishOnly) {
    const buildEnvPath = process.env.CRAYS_TEST_ROOM_BUILD_ENV || '.env.test-room-build';
    writeFileSync(buildEnvPath, [
      '# Generated by npm run test-room:publish. The invite is intentionally public in test builds.',
      'EXPO_PUBLIC_CRAYS_TEST_BUILD=1',
      `EXPO_PUBLIC_CRAYS_TEST_RELAY_URL=${state.relay_url}`,
      `EXPO_PUBLIC_CRAYS_TEST_ROOM_ID=${state.room_id}`,
      `EXPO_PUBLIC_CRAYS_TEST_ROOM_SERVICE_URL=${state.base_url}`,
      `EXPO_PUBLIC_CRAYS_TEST_ROOM_INVITE_TOKEN=${state.invite_token}`,
      '',
    ].join('\n'), { mode: 0o600 });
    console.log('\nTEST ROOM PUBLISHED');
    console.log(`Room: ${roomName} (${roomId})`);
    console.log(`Relay: ${state.relay_url}`);
    console.log(`Invite expires: ${new Date(state.invite_expires_at * 1000).toISOString()}`);
    console.log(`Test-build environment: ${buildEnvPath}`);
    console.log('The hosted relay owns runtime access; no local process or invite proxy is required.');
    relayCreated = false;
    process.exit(0);
  }

  if (proxyEnabled) {
    server = http.createServer(async (request, response) => {
      if (request.url === '/healthz') {
        response.writeHead(200, { 'content-type': 'application/json' });
        response.end(JSON.stringify({ ok: true, room_id: state.room_id, relay_url: state.relay_url }));
        return;
      }
      if (request.method === 'GET' && (request.headers.accept || '').includes('application/nostr+json')) {
        // NIP-11 passthrough for the explicit local-proxy mode.
        try {
          const upstreamHttp = state.relay_url.replace(/^ws/, 'http');
          const upstream = await fetch(`${upstreamHttp}${request.url}`, { headers: { accept: 'application/nostr+json' } });
          response.writeHead(upstream.status, { 'content-type': upstream.headers.get('content-type') || 'application/nostr+json' });
          response.end(Buffer.from(await upstream.arrayBuffer()));
        } catch (error) {
          response.writeHead(502, { 'content-type': 'application/json' });
          response.end(JSON.stringify({ error: `Test Room relay document unavailable: ${error.message}` }));
        }
        return;
      }
      response.writeHead(404).end();
    });
    sockets = new WebSocketServer({ server });
    sockets.on('connection', (client) => {
      const upstream = new WebSocket(state.relay_url);
      const pending = [];
      client.on('message', (data, binary) => {
        if (upstream.readyState === WebSocket.OPEN) upstream.send(data, { binary });
        else if (upstream.readyState === WebSocket.CONNECTING) pending.push([data, binary]);
      });
      upstream.on('open', () => {
        for (const [data, binary] of pending.splice(0)) upstream.send(data, { binary });
      });
      upstream.on('message', (data, binary) => {
        if (client.readyState === WebSocket.OPEN) client.send(data, { binary });
      });
      client.on('close', () => upstream.close());
      client.on('error', () => upstream.close());
      upstream.on('close', (code, reason) => client.readyState < WebSocket.CLOSING && client.close(wireCloseCode(code), reason));
      upstream.on('error', () => client.readyState < WebSocket.CLOSING && client.close(1011, 'upstream relay unavailable'));
    });
    await new Promise((resolve, reject) => {
      server.once('error', reject);
      server.listen(proxyPort, '0.0.0.0', resolve);
    });
  } else {
    // Keep the local lifecycle owner alive until stopped while the app connects
    // directly to the hosted relay. No local WebSocket or invite endpoint is involved.
    keepAlive = setInterval(() => {}, 60_000);
  }
  writeFileSync(pidPath, `${process.pid}\n`, { flag: 'wx' });
  process.on('SIGINT', () => void stop('SIGINT'));
  process.on('SIGTERM', () => void stop('SIGTERM'));
  console.log('\nTEST ROOM READY');
  console.log(`Room: ${roomName} (${roomId})`);
  console.log(`Invite expires: ${new Date(state.invite_expires_at * 1000).toISOString()}`);
  console.log(`Invite redemptions: ${state.invite_max_redemptions}`);
  if (proxyEnabled) {
    console.log(`Proxy relay (Android emulator): ws://10.0.2.2:${proxyPort}`);
    console.log(`Proxy relay (iOS simulator): ws://127.0.0.1:${proxyPort}`);
  } else {
    console.log(`Direct relay: ${state.relay_url}`);
  }
  console.log('Keep this process running. Visible entry redeems the direct broadcast invite; quiet entry does not.');
} catch (error) {
  console.error(`Test room failed: ${error.message}`);
  teardown();
  rmSync(pidPath, { force: true });
  process.exit(1);
}
