// THESIS: Me is a calm urgency-ranked archive; Wallet is a discreet operational rail.
// OWNED WORLD: Durable rows resemble a well-kept coat-check ledger, not a finance dashboard.
// STORY: Resolve active item → find history/access → inspect honest account and wallet readiness.
// FIRST VIEWPORT: Active-now context and durable categories precede settings.
// FORM: Empty, hidden balance, recovering, mint unavailable, and unconfigured states are explicit.
import { Ionicons } from '@expo/vector-icons';
import { Pressable, Text, View } from 'react-native';
import { AppShell, RaisedRow, SectionTitle } from '@/components/app/AppShell';
import { PrimaryButton } from '@/components/onboarding/OnboardingPrimitives';
import type { RoomOrder } from '@/rooms/types';
import { colors } from '@/theme/colors';
import { orderStatusLabel } from '@/screens/durable/NightAndOrderScreens';

export function MeScreen({ activeOrder, error, hasMembership, onMemberships, onOrders, onProfile, onTickets, onWallet, roomName, ticketCount }: { activeOrder?: RoomOrder; error?: string | null; hasMembership: boolean; onMemberships: () => void; onOrders: () => void; onProfile: () => void; onTickets: () => void; onWallet: () => void; roomName?: string; ticketCount: number }) {
  const row = (icon: keyof typeof Ionicons.glyphMap, title: string, detail: string, action: () => void, id: string) => <Pressable accessibilityLabel={title} accessibilityRole="button" onPress={action} testID={id}><RaisedRow><Ionicons color={colors.accent} name={icon} size={25} /><View className="ml-4 flex-1"><Text className="text-base font-black text-base-content">{title}</Text><Text className="mt-1 text-sm text-muted">{detail}</Text></View><Ionicons color={colors.accent} name="chevron-forward" size={21} /></RaisedRow></Pressable>;
  return <AppShell eyebrow="Your Crays" testID="me-screen" title="Me">{error ? <Text accessibilityRole="alert" className="mt-4 text-sm text-error">{error}</Text> : null}{activeOrder ? <><SectionTitle>Active now</SectionTitle><Pressable accessibilityLabel="Track active order" accessibilityRole="button" onPress={onOrders}><View className="rounded-[24px] bg-primary p-5"><Text className="text-xs font-black uppercase tracking-[2px] text-white/80">{roomName || 'Current room'}</Text><Text className="mt-2 text-xl font-black text-white">{activeOrder.product.name}</Text><Text className="mt-1 text-white/90">{orderStatusLabel(activeOrder.status)} · order {activeOrder.orderRef}</Text></View></Pressable></> : null}<SectionTitle>Keep and manage</SectionTitle><View className="gap-3">{row('receipt-outline', 'Orders', activeOrder ? 'Track active order and receipts' : 'History, receipts and support', onOrders, 'me-orders')}{row('ribbon-outline', 'Memberships & passes', hasMembership ? 'Active room membership' : 'Offers and durable access', onMemberships, 'me-memberships')}{row('ticket-outline', 'Tickets', ticketCount ? `${ticketCount} relay-confirmed ${ticketCount === 1 ? 'ticket' : 'tickets'}` : 'Upcoming and past event access', onTickets, 'me-tickets')}{row('wallet-outline', 'Wallet', 'Not set up · balance unavailable', onWallet, 'me-wallet')}</View><SectionTitle>Profile & settings</SectionTitle>{row('person-circle-outline', 'Profile, privacy & account', 'Identity, recovery, notifications and blocks', onProfile, 'me-profile')}</AppShell>;
}

export function WalletScreen({ onAddFunds, onBack }: { onAddFunds: () => void; onBack: () => void }) { return <AppShell eyebrow="Me" testID="wallet-screen" title="Wallet"><Pressable accessibilityRole="button" className="mt-1 flex-row items-center gap-2 self-start" onPress={onBack}><Ionicons color={colors.accent} name="arrow-back" size={18} /><Text className="font-bold text-primary">Back to Me</Text></Pressable><View className="mt-7 rounded-[30px] border border-base-300 bg-base-200 p-6"><Text className="text-xs font-black uppercase tracking-[2px] text-muted">Spendable balance</Text><Text className="mt-3 text-[44px] font-black text-base-content">Unavailable</Text><Text className="mt-2 leading-6 text-muted">No trusted Cashu mint or encrypted NIP-60 wallet has been configured for this build.</Text></View><View className="mt-5"><PrimaryButton disabled label="Wallet setup required" onPress={onAddFunds} testID="wallet-setup-disabled" /></View><SectionTitle>Actions</SectionTitle><View className="gap-3"><Pressable accessibilityRole="button" onPress={onAddFunds} testID="wallet-add-funds"><RaisedRow><Ionicons color={colors.accent} name="add-circle-outline" size={26} /><Text className="ml-4 flex-1 font-bold text-base-content">Add funds</Text><Ionicons color={colors.accent} name="chevron-forward" size={21} /></RaisedRow></Pressable><RaisedRow><Ionicons color={colors.placeholder} name="arrow-down-circle-outline" size={26} /><View className="ml-4 flex-1"><Text className="font-bold text-muted">Receive</Text><Text className="mt-1 text-sm text-muted">Available after wallet setup</Text></View></RaisedRow></View><SectionTitle>Recovery & activity</SectionTitle><RaisedRow><Ionicons color={colors.accent} name="cloud-offline-outline" size={25} /><View className="ml-4 flex-1"><Text className="font-bold text-base-content">Nostr sync not configured</Text><Text className="mt-1 text-sm leading-5 text-muted">No balance or proof state is fabricated. Recovery remains unavailable until an encrypted wallet is created.</Text></View></RaisedRow></AppShell>; }

export function AddFundsScreen({ onBack }: { onBack: () => void }) { return <AppShell eyebrow="Wallet" testID="add-funds-screen" title="Add funds"><Pressable accessibilityRole="button" className="mt-1 flex-row items-center gap-2 self-start" onPress={onBack}><Ionicons color={colors.accent} name="arrow-back" size={18} /><Text className="font-bold text-primary">Back to Wallet</Text></Pressable><View className="mt-8 items-center rounded-[30px] border border-base-300 bg-base-200 p-7"><View className="h-16 w-16 items-center justify-center rounded-full bg-primary/15"><Ionicons color={colors.accent} name="flash-outline" size={32} /></View><Text className="mt-5 text-2xl font-black text-base-content">Lightning funding is not configured</Text><Text className="mt-3 text-center leading-6 text-muted">A funding request needs a selected Cashu mint, a real Lightning quote, expiry, and recoverable proof state. This build creates none of those.</Text></View><SectionTitle>When enabled</SectionTitle>{['Enter an amount in EUR', 'Review the live Lightning quote and expiry', 'Credit only after mint proofs verify and sync safely'].map((text, index) => <View className="mb-3 flex-row items-center" key={text}><View className="h-8 w-8 items-center justify-center rounded-full bg-primary"><Text className="font-black text-white">{index + 1}</Text></View><Text className="ml-3 flex-1 leading-6 text-base-content">{text}</Text></View>)}<View className="mt-6"><PrimaryButton disabled label="Mint configuration required" onPress={() => {}} testID="add-funds-disabled" /></View></AppShell>; }
