import { Ionicons } from '@expo/vector-icons';
import { Pressable, Text, View } from 'react-native';

import type { DurableTicket } from '@/access/tickets';
import type { RoomEntitlement } from '@/rooms/types';
import { EntitlementPresentation } from '@/components/durable/EntitlementPresentation';
import { AppShell, RaisedRow, SectionTitle } from '@/components/app/AppShell';
import { PrimaryButton } from '@/components/onboarding/OnboardingPrimitives';
import { colors } from '@/theme/colors';

export function TicketsScreen({ entitlements = [], now, onBack, onOpen, onOpenEntitlement, tickets }: { entitlements?: RoomEntitlement[]; now: number; onBack: () => void; onOpen: (ticket: DurableTicket) => void; onOpenEntitlement?: (item: RoomEntitlement) => void; tickets: DurableTicket[] }) {
  const upcoming = tickets.filter((ticket) => !ticket.end || ticket.end >= now);
  const past = tickets.filter((ticket) => ticket.end && ticket.end < now);
  const rows = (items: DurableTicket[]) => <View className="gap-3">{items.map((ticket) => <Pressable accessibilityLabel={`Open ticket ${ticket.title}`} accessibilityRole="button" key={ticket.id} onPress={() => onOpen(ticket)} testID={`ticket-row-${ticket.eventId}`}><RaisedRow><View className="h-12 w-12 items-center justify-center rounded-xl bg-white"><Ionicons color={colors.night} name="ticket-outline" size={27} /></View><View className="ml-4 flex-1"><Text className="text-lg font-black text-base-content">{ticket.title}</Text><Text className="mt-1 text-sm text-muted">{ticket.roomName} · {new Date(ticket.start * 1000).toLocaleDateString()}</Text></View><Ionicons color={colors.accent} name="chevron-forward" size={22} /></RaisedRow></Pressable>)}</View>;
  const issued = entitlements.filter((item) => item.type === 'event_access');
  return <AppShell eyebrow="Me" testID="tickets-screen" title="Tickets"><Pressable accessibilityRole="button" className="mt-1 flex-row items-center gap-2 self-start" onPress={onBack}><Ionicons color={colors.accent} name="arrow-back" size={18} /><Text className="font-bold text-primary">Back to Me</Text></Pressable>{issued.length ? <><SectionTitle>Ready at the door</SectionTitle><View className="gap-3">{issued.map((item) => <Pressable accessibilityLabel={`Open ${item.name}`} accessibilityRole="button" key={item.awardId} onPress={() => onOpenEntitlement?.(item)} testID={`ticket-award-${item.awardId}`}><RaisedRow><View className="h-12 w-12 items-center justify-center rounded-xl bg-white"><Ionicons color={colors.night} name="qr-code-outline" size={27} /></View><View className="ml-4 flex-1"><Text className="text-lg font-black text-base-content">{item.name}</Text><Text className="mt-1 text-sm text-muted">{item.roomName} · {item.state === 'available' ? 'Live code available' : item.state}</Text></View><Ionicons color={colors.accent} name="chevron-forward" size={22} /></RaisedRow></Pressable>)}</View></> : null}{upcoming.length ? <><SectionTitle>RSVPs</SectionTitle>{rows(upcoming)}</> : !issued.length ? <View className="mt-10 items-center rounded-[28px] border border-dashed border-base-300 p-8"><Ionicons color={colors.accent} name="ticket-outline" size={37} /><Text className="mt-4 text-xl font-black text-base-content">No upcoming tickets</Text><Text className="mt-2 text-center leading-6 text-muted">A relay-confirmed event RSVP or ticket appears here and remains after leaving.</Text></View> : null}{past.length ? <><SectionTitle>Past RSVPs</SectionTitle>{rows(past)}</> : null}</AppShell>;
}

function TicketBackLink({ onBack }: { onBack: () => void }) {
  return <Pressable accessibilityLabel="All tickets" accessibilityRole="button" className="-ml-3 mt-1 min-h-12 flex-row items-center gap-2 self-start px-3" hitSlop={8} onPress={onBack} testID="ticket-detail-back"><Ionicons color={colors.accent} name="arrow-back" size={18} /><Text className="font-bold text-primary">All tickets</Text></Pressable>;
}

export function TicketDetailScreen({ entitlement, onBack, ticket }: { entitlement?: RoomEntitlement; onBack: () => void; ticket?: DurableTicket }) {
  if (entitlement) return <AppShell eyebrow={entitlement.roomName} testID="ticket-detail-screen" title="Event ticket"><TicketBackLink onBack={onBack} /><View className="mt-7 rounded-[30px] border border-base-300 bg-base-200 p-6"><Text className="text-xs font-black uppercase tracking-[2px] text-success">{entitlement.state === 'available' ? 'Ready to show' : entitlement.state}</Text><Text className="mt-3 text-3xl font-black text-base-content">{entitlement.name}</Text><Text className="mt-3 leading-6 text-muted">{entitlement.description}</Text></View><SectionTitle>At the door</SectionTitle><EntitlementPresentation item={entitlement} /><Text className="mt-4 leading-6 text-muted">This code refreshes automatically and is signed for you. Staff checks your ticket and its current status at the door.</Text>{entitlement.activity.length ? <><SectionTitle>Entry activity</SectionTitle>{entitlement.activity.map((activity) => <RaisedRow key={activity.id}><Ionicons color={colors.accent} name="checkmark-circle-outline" size={24} /><Text className="ml-4 flex-1 font-bold text-base-content">{activity.status} · {new Date(activity.createdAt * 1000).toLocaleString()}</Text></RaisedRow>)}</> : null}</AppShell>;
  if (!ticket) return <AppShell testID="ticket-detail-screen" title="Ticket"><Text className="mt-10 text-xl font-black text-base-content">Ticket unavailable</Text><Text className="mt-2 leading-6 text-muted">No saved RSVP or active entry ticket matches this link.</Text><View className="mt-6"><PrimaryButton label="Back to tickets" onPress={onBack} /></View></AppShell>;
  return <AppShell eyebrow={ticket.roomName} testID="ticket-detail-screen" title="Event ticket"><TicketBackLink onBack={onBack} /><View className="mt-7 rounded-[30px] border border-base-300 bg-base-200 p-6"><Text className="text-xs font-black uppercase tracking-[2px] text-success">RSVP saved</Text><Text className="mt-3 text-3xl font-black text-base-content">{ticket.title}</Text><Text className="mt-3 leading-6 text-muted">{new Date(ticket.start * 1000).toLocaleString()} · {ticket.location}</Text></View><SectionTitle>At the door</SectionTitle><View className="items-center rounded-[26px] bg-white p-7"><Ionicons color={colors.night} name="qr-code-outline" size={150} /><Text className="mt-3 text-center text-sm font-bold text-paper-ink">No entry code yet</Text></View><Text className="mt-4 leading-6 text-muted">This RSVP confirms your plans, but it is not an entry code. A live code appears only after the venue issues ticket access.</Text></AppShell>;
}
