// THESIS: Changing room state is a deliberate privacy boundary, not a navigation side effect.
// OWNED WORLD: A closing door card names what ends and what remains in the person's pocket.
// STORY: Name current state → confirm end/switch → preserve durable objects → choose next place.
// FIRST VIEWPORT: Current and destination room plus the precise consequence are visible.
// FORM: Publishing, destination failure, cancel, quiet leave, and completed lock states are explicit.
import { Ionicons } from '@expo/vector-icons';
import { ActivityIndicator, Text, View } from 'react-native';
import { AppShell, RaisedRow } from '@/components/app/AppShell';
import { PrimaryButton, TextAction } from '@/components/onboarding/OnboardingPrimitives';
import type { ActiveRoom, RoomDescriptor } from '@/rooms/types';
import { colors } from '@/theme/colors';

export function LeaveRoomScreen({ error, leaving, onCancel, onLeave, room }: { error?: string | null; leaving: boolean; onCancel: () => void; onLeave: () => void; room: ActiveRoom }) { return <AppShell eyebrow="Privacy control" testID="leave-room-screen" title="Leave room"><View className="mt-7 items-center rounded-[30px] border border-base-300 bg-base-200 p-7"><View className="h-16 w-16 items-center justify-center rounded-full bg-primary/15"><Ionicons color={colors.accent} name="exit-outline" size={32} /></View><Text className="mt-5 text-center text-2xl font-black text-base-content">Leave {room.name}?</Text><Text className="mt-3 text-center leading-6 text-muted">Your live presence ends and the room feed locks. Messages, orders, tickets, passes, and memberships stay yours.</Text></View><View className="mt-5 gap-3"><RaisedRow><Ionicons color={colors.accent} name="eye-off-outline" size={24} /><Text className="ml-4 flex-1 font-bold text-base-content">Stop appearing in People</Text></RaisedRow><RaisedRow><Ionicons color={colors.accent} name="lock-closed-outline" size={24} /><Text className="ml-4 flex-1 font-bold text-base-content">Stop room feed access</Text></RaisedRow><RaisedRow><Ionicons color={colors.accent} name="archive-outline" size={24} /><Text className="ml-4 flex-1 font-bold text-base-content">Keep durable items and conversations</Text></RaisedRow></View>{error ? <Text className="mt-4 text-error">{error}</Text> : null}<View className="mt-auto pt-8"><PrimaryButton label="Leave room and hide me" loading={leaving} onPress={onLeave} testID="leave-room-confirm" /><TextAction label="Stay in the room" onPress={onCancel} testID="leave-room-cancel" /></View></AppShell>; }

export function RoomEndedScreen({ automatic = false, onDiscover, onMessages, previousRoomName }: { automatic?: boolean; onDiscover: () => void; onMessages: () => void; previousRoomName: string }) { return <AppShell eyebrow="Privacy complete" testID="room-ended-screen" title="Room ended"><View className="mt-8 items-center"><View className="h-20 w-20 items-center justify-center rounded-full bg-success/15"><Ionicons color="#20b878" name="checkmark-circle-outline" size={46} /></View><Text accessibilityRole="header" className="mt-6 text-center text-[38px] font-black leading-[41px] text-base-content">{automatic ? `Your time at ${previousRoomName} ended.` : `You’ve left ${previousRoomName}.`}</Text><Text className="mt-4 text-center text-lg leading-7 text-muted">{automatic ? 'Your automatic leave time passed.' : 'Your presence ended.'} The live feed is locked. Nothing announces that you left.</Text></View><View className="mt-8 rounded-2xl bg-base-200 p-5"><Text className="text-xs font-black uppercase tracking-[2px] text-primary">Still with you</Text><Text className="mt-3 leading-7 text-base-content">Private messages · orders and receipts · tickets · passes · memberships · wallet state</Text></View><View className="mt-auto pt-8"><PrimaryButton label="Discover another room" onPress={onDiscover} testID="room-ended-discover" /><TextAction label="Open Messages" onPress={onMessages} testID="room-ended-messages" /></View></AppShell>; }

export function SwitchRoomScreen({ current, destination, error, loading, onCancel, onSwitch, switching }: { current: ActiveRoom; destination: RoomDescriptor | null; error?: string | null; loading: boolean; onCancel: () => void; onSwitch: () => void; switching: boolean }) { return <AppShell eyebrow="One room at a time" testID="switch-room-screen" title="Switch rooms"><View className="mt-7 flex-row items-center justify-center gap-3"><View className="flex-1 rounded-[24px] border border-base-300 bg-base-200 p-5"><Text className="text-xs font-black uppercase text-muted">Leaving</Text><Text className="mt-2 text-lg font-black text-base-content">{current.name}</Text></View><Ionicons color={colors.accent} name="arrow-forward" size={24} /><View className="flex-1 rounded-[24px] border border-primary/50 bg-primary/10 p-5"><Text className="text-xs font-black uppercase text-primary">Entering</Text>{loading ? <ActivityIndicator className="mt-3" /> : <Text className="mt-2 text-lg font-black text-base-content">{destination?.name || 'Unavailable'}</Text>}</View></View><Text className="mt-7 text-base leading-7 text-muted">Switching ends presence and feed access at {current.name}. Messages, active orders, tickets, passes, memberships, and wallet state remain.</Text>{error ? <Text className="mt-4 text-error">{error}</Text> : null}<View className="mt-auto pt-8"><PrimaryButton disabled={!destination} label="Leave and enter new room" loading={switching} onPress={onSwitch} testID="switch-room-confirm" /><TextAction label={`Stay in ${current.name}`} onPress={onCancel} testID="switch-room-cancel" /></View></AppShell>; }
