// THESIS: Gift review separates purchaser, recipient, delivery, acceptance, and fulfillment.
// OWNED WORLD: One dual-name ticket makes the social and commerce contract concrete.
// STORY: Recheck people and item → understand decline/refund → inspect method → pay only on a real rail.
// FIRST VIEWPORT: Recipient, item, total, and decline/refund consequence are visible.
// FORM: Recipient departure, decline, refund pending, and deferred payment cannot masquerade as success.
import { Ionicons } from '@expo/vector-icons';
import { Pressable, Text, View } from 'react-native';

import { AppShell } from '@/components/app/AppShell';
import type { CartLine } from '@/commerce/Cart';
import { formatCurrency } from '@/commerce/currency';
import { colors } from '@/theme/colors';

export function GiftReviewScreen({ line, method, onBack, onChangeMethod }: { line: CartLine; method: string; onBack: () => void; onChangeMethod: () => void }) {
  const total = line.price * line.quantity;
  return <AppShell eyebrow="Gift order" testID="gift-review-screen" title="Review the gift"><Pressable accessibilityRole="button" className="mt-1 min-h-12 flex-row items-center gap-2 self-start" onPress={onBack}><Ionicons color={colors.accent} name="arrow-back" size={18} /><Text className="font-bold text-primary">Choose another drink</Text></Pressable><View className="mt-6 rounded-[30px] border border-base-300 bg-base-200 p-6"><View className="flex-row items-center gap-4"><View className="h-14 w-14 items-center justify-center rounded-full bg-primary/15"><Text className="text-2xl font-black text-primary">{line.recipientName?.slice(0, 1)}</Text></View><View><Text className="text-xs font-black uppercase tracking-[2px] text-muted">Recipient</Text><Text className="mt-1 text-2xl font-black text-base-content">{line.recipientName}</Text></View></View><View className="my-5 h-px bg-base-300" /><View className="flex-row justify-between"><View className="flex-1"><Text className="text-xl font-extrabold text-base-content">{line.name}</Text><Text className="mt-1 text-sm text-muted">Quantity {line.quantity} · from you</Text></View><Text className="text-xl font-black text-base-content">{formatCurrency(total, line.currency)}</Text></View></View><View className="mt-5 gap-3"><View className="flex-row gap-3 rounded-2xl bg-base-200 p-4"><Ionicons color={colors.accent} name="restaurant-outline" size={22} /><Text className="flex-1 text-sm leading-5 text-base-content">The bar receives a normal order. {line.recipientName} receives a private message and claim ticket.</Text></View><View className="flex-row gap-3 rounded-2xl bg-base-200 p-4"><Ionicons color={colors.accent} name="return-down-back-outline" size={22} /><Text className="flex-1 text-sm leading-5 text-base-content">They may decline before fulfillment. Refund follows the original payment rail and may show Refund pending first.</Text></View></View><Pressable className="mt-5 flex-row items-center rounded-2xl border border-base-300 bg-base-200 p-4" onPress={onChangeMethod} testID="gift-payment-method"><Ionicons color={colors.accent} name="wallet-outline" size={24} /><View className="ml-4 flex-1"><Text className="text-xs font-black uppercase tracking-[2px] text-muted">Payment method</Text><Text className="mt-1 text-lg font-extrabold text-base-content">{method}</Text></View><Ionicons color={colors.accent} name="chevron-forward" size={22} /></Pressable><View className="mt-5 rounded-2xl border border-primary/20 bg-primary/10 p-4"><Text className="text-sm leading-5 text-base-content">Payment is intentionally deferred in this pilot. No order or gift ticket is created.</Text></View><Pressable accessibilityState={{ disabled: true }} className="mt-6 min-h-14 items-center justify-center rounded-2xl bg-base-300" disabled testID="pay-gift-disabled"><Text className="font-black text-muted">Payment unavailable · {formatCurrency(total, line.currency)}</Text></Pressable></AppShell>;
}
