import { fireEvent, render } from '@testing-library/react-native';
import { AddFundsScreen, MeScreen, WalletScreen } from '@/screens/durable/AccountWalletScreens';
import { EventScreen, MembershipDetailScreen, MembershipOfferScreen, MembershipsScreen } from '@/screens/durable/MembershipEventScreens';
import { MyNightScreen, OrderDetailScreen, OrdersScreen } from '@/screens/durable/NightAndOrderScreens';
import type { RoomCalendarEvent, RoomEntitlement, RoomMembershipOffer, RoomOrder } from '@/rooms/types';

jest.mock('@/components/durable/EntitlementPresentation', () => ({ EntitlementPresentation: () => null }));

const product = { id: 'product', address: `30009:${'a'.repeat(64)}:drink`, name: 'Negroni', description: 'Smoky', price: 12, currency: 'EUR', section: 'Cocktails', productKind: 'drink', available: true, position: 0 };
const order: RoomOrder = { id: 'order', awardId: 'award', orderRef: 'CR-42', product, status: 'ready', createdAt: 1, updatedAt: 2, recipientPubkey: 'b'.repeat(64) };
const membership: RoomMembershipOffer = { id: 'member', address: `30009:${'a'.repeat(64)}:member`, name: 'Skyline Regular', description: 'Monthly perks', price: 24, currency: 'EUR', billing: 'monthly', available: true };
const event: RoomCalendarEvent = { id: 'event', address: `31923:${'a'.repeat(64)}:jazz`, title: 'Rooftop Jazz', summary: 'Under the stars', location: 'Roof', start: 2_000_000_000, end: null, capacity: 18, price: 0, currency: 'EUR' };
const entitlement: RoomEntitlement = { awardId: 'c'.repeat(64), badgeAddress: membership.address, awardIssuerPubkey: 'd'.repeat(64), recipientPubkey: 'e'.repeat(64), definitionId: membership.id, definitionIssuerPubkey: 'a'.repeat(64), type: 'membership', name: membership.name, description: membership.description, billing: membership.billing, state: 'active', orderRef: 'member', createdAt: 1, activity: [], roomId: 'skyline', roomName: 'Skyline', relayUrl: 'wss://relay.example' };

describe('durable screens', () => {
  it('connects every My night object to its exact action', () => { const open = jest.fn(); const view = render(<MyNightScreen event={event} membership={membership} order={order} roomName="Skyline" onBack={jest.fn()} onEvent={open} onMembership={jest.fn()} onOrder={jest.fn()} />); fireEvent.press(view.getByTestId('my-night-event')); expect(open).toHaveBeenCalled(); expect(view.getByText('Ready')).toBeTruthy(); });
  it('groups active orders and opens relay-derived detail', () => { const open = jest.fn(); const view = render(<OrdersScreen orders={[order]} onBack={jest.fn()} onOpen={open} />); fireEvent.press(view.getByTestId('order-row-CR-42')); expect(open).toHaveBeenCalledWith(order); });
  it('maps processing status to user language and never Delivered', () => { const view = render(<OrderDetailScreen onBack={jest.fn()} order={{ ...order, status: 'processing' }} roomName="Skyline" />); expect(view.getAllByText('Preparing').length).toBeGreaterThan(0); expect(view.queryByText('Delivered')).toBeNull(); });
  it('routes urgency-ranked Me rows', () => { const wallet = jest.fn(); const tickets = jest.fn(); const view = render(<MeScreen activeOrder={order} hasMembership ticketCount={1} onMemberships={jest.fn()} onOrders={jest.fn()} onProfile={jest.fn()} onTickets={tickets} onWallet={wallet} roomName="Skyline" />); fireEvent.press(view.getByTestId('me-wallet')); fireEvent.press(view.getByTestId('me-tickets')); expect(wallet).toHaveBeenCalled(); expect(tickets).toHaveBeenCalled(); });
  it('keeps membership purchase disabled without payment rails', () => { const view = render(<MembershipOfferScreen membership={membership} onBack={jest.fn()} onPaymentMethods={jest.fn()} roomName="Skyline" />); expect(view.getByTestId('membership-purchase-disabled').props.accessibilityState.disabled).toBe(true); });
  it('shows explicit active membership and a presentation surface', () => { const view = render(<MembershipDetailScreen entitlement={entitlement} membership={membership} onBack={jest.fn()} roomName="Skyline" />); expect(view.getByText('Active')).toBeTruthy(); expect(view.getByText('Present membership')).toBeTruthy(); });
  it('groups durable access and opens the exact award', () => { const open = jest.fn(); const pass = { ...entitlement, awardId: 'f'.repeat(64), type: 'pass' as const, name: 'Three visits', state: 'available' as const, maxUses: 3, remainingUses: 2 }; const view = render(<MembershipsScreen entitlements={[entitlement, pass]} onBack={jest.fn()} onOpen={open} />); expect(view.getByText(/2 uses left/)).toBeTruthy(); fireEvent.press(view.getByTestId(`entitlement-row-${pass.awardId}`)); expect(open).toHaveBeenCalledWith(pass); });
  it('publishes only through the RSVP action for a free event', () => { const rsvp = jest.fn(); const view = render(<EventScreen event={event} going={false} loading={false} onBack={jest.fn()} onRsvp={rsvp} roomName="Skyline" />); fireEvent.press(view.getByTestId('event-rsvp')); expect(rsvp).toHaveBeenCalled(); });
  it('does not fabricate wallet money or funding', () => { const wallet = render(<WalletScreen onAddFunds={jest.fn()} onBack={jest.fn()} />); expect(wallet.getByText('Unavailable')).toBeTruthy(); wallet.unmount(); const funds = render(<AddFundsScreen onBack={jest.fn()} />); expect(funds.getByTestId('add-funds-disabled').props.accessibilityState.disabled).toBe(true); });
});
