import { fireEvent, render } from '@testing-library/react-native';
import type { DurableTicket } from '@/access/tickets';
import { AddFundsScreen, MeScreen, WalletScreen } from '@/screens/durable/AccountWalletScreens';
import { EventScreen, MembershipDetailScreen, MembershipOfferScreen, MembershipsScreen } from '@/screens/durable/MembershipEventScreens';
import { MyNightScreen, OrderDetailScreen, OrdersScreen } from '@/screens/durable/NightAndOrderScreens';
import { myNightDoorDestination, selectMyNightDoorItem } from '@/screens/durable/myNight';
import type { RoomCalendarEvent, RoomEntitlement, RoomMembershipOffer, RoomOrder } from '@/rooms/types';

jest.mock('@/components/durable/EntitlementPresentation', () => ({ EntitlementPresentation: () => null }));

const product = { id: 'product', address: `30009:${'a'.repeat(64)}:drink`, name: 'Negroni', description: 'Smoky', price: 12, currency: 'EUR', section: 'Cocktails', productKind: 'drink', available: true, position: 0 };
const order: RoomOrder = { id: 'order', awardId: 'award', orderRef: 'CR-42', product, status: 'ready', createdAt: 1, updatedAt: 2, recipientPubkey: 'b'.repeat(64) };
const membership: RoomMembershipOffer = { id: 'member', address: `30009:${'a'.repeat(64)}:member`, name: 'Skyline Regular', description: 'Monthly perks', price: 24, currency: 'EUR', billing: 'monthly', available: true };
const event: RoomCalendarEvent = { id: 'event', address: `31923:${'a'.repeat(64)}:jazz`, title: 'Rooftop Jazz', summary: 'Under the stars', location: 'Roof', start: 2_000_000_000, end: null, capacity: 18, price: 0, currency: 'EUR' };
const entitlement: RoomEntitlement = { awardId: 'c'.repeat(64), badgeAddress: membership.address, awardIssuerPubkey: 'd'.repeat(64), recipientPubkey: 'e'.repeat(64), definitionId: membership.id, definitionIssuerPubkey: 'a'.repeat(64), type: 'membership', name: membership.name, description: membership.description, billing: membership.billing, state: 'active', orderRef: 'member', createdAt: 1, activity: [], roomId: 'skyline', roomName: 'Skyline', relayUrl: 'wss://relay.example' };
const eventAccess: RoomEntitlement = { ...entitlement, awardId: 'f'.repeat(64), badgeAddress: `30402:${'a'.repeat(64)}:jazz-entry`, definitionId: 'jazz-entry', type: 'event_access', name: 'Rooftop Jazz entry', description: 'Door entry', eventAddress: event.address, state: 'available', orderRef: '' };
const ticket: DurableTicket = { id: 'ticket', eventAddress: event.address, eventId: event.id, title: event.title, summary: event.summary, location: event.location, start: event.start, end: event.end, roomId: 'skyline', roomName: 'Skyline', relayUrl: 'wss://relay.example', status: 'going', confirmedAt: 2 };

describe('durable screens', () => {
  it('prioritizes an event-access award and routes its exact award ID to the live ticket', () => { const doorItem = selectMyNightDoorItem({ entitlements: [eventAccess], events: [event], now: 1_900_000_000, roomId: 'skyline', tickets: [ticket] }); expect(doorItem).toEqual({ kind: 'credential', awardId: eventAccess.awardId, title: event.title, location: event.location }); expect(myNightDoorDestination(doorItem!)).toEqual({ pathname: '/ticket', params: { awardId: eventAccess.awardId } }); });
  it('labels calendar-only events as events instead of scanner credentials', () => { const doorItem = selectMyNightDoorItem({ entitlements: [], events: [event], now: 1_900_000_000, roomId: 'skyline', tickets: [] }); const view = render(<MyNightScreen doorItem={doorItem} roomName="Skyline" onBack={jest.fn()} onDoorItem={jest.fn()} onMembership={jest.fn()} onOrder={jest.fn()} />); expect(view.getByText('Coming up')).toBeTruthy(); expect(view.getByText('Roof · View event')).toBeTruthy(); expect(view.queryByText(/show at the door/i)).toBeNull(); });
  it('connects every My night object to its exact action without exposing the order reference', () => { const open = jest.fn(); const doorItem = selectMyNightDoorItem({ entitlements: [eventAccess], events: [event], now: 1_900_000_000, roomId: 'skyline', tickets: [] }); const view = render(<MyNightScreen doorItem={doorItem} membership={membership} order={order} roomName="Skyline" onBack={jest.fn()} onDoorItem={open} onMembership={jest.fn()} onOrder={jest.fn()} />); fireEvent.press(view.getByTestId('my-night-event')); expect(open).toHaveBeenCalled(); expect(view.getByText('Live code ready', { exact: false })).toBeTruthy(); expect(view.getByText('Ready')).toBeTruthy(); expect(view.queryByText(order.orderRef, { exact: false })).toBeNull(); expect(view.getByTestId('my-night-back').props.className).toContain('min-h-12'); });
  it('groups active orders, hides internal references, and opens relay-derived detail', () => { const open = jest.fn(); const view = render(<OrdersScreen orders={[order]} onBack={jest.fn()} onOpen={open} />); fireEvent.press(view.getByTestId(`order-row-${order.id}`)); expect(open).toHaveBeenCalledWith(order); expect(view.queryByText(order.orderRef, { exact: false })).toBeNull(); expect(view.getByTestId('orders-back').props.className).toContain('min-h-12'); });
  it('maps processing and cancellation states to customer language without internal terms', () => { const view = render(<OrderDetailScreen onBack={jest.fn()} order={{ ...order, status: 'processing' }} roomName="Skyline" />); expect(view.getAllByText('Preparing').length).toBeGreaterThan(0); expect(view.getByText('The venue updates this status as your order moves forward.')).toBeTruthy(); expect(view.getByText('Payment details appear after payment is confirmed.')).toBeTruthy(); expect(view.queryByText(order.orderRef, { exact: false })).toBeNull(); expect(view.queryByText(/payment rail|venue relay/i)).toBeNull(); expect(view.queryByText('Delivered')).toBeNull(); expect(view.getByTestId('order-detail-back').props.className).toContain('min-h-12'); view.unmount(); const cancelled = render(<OrderDetailScreen onBack={jest.fn()} order={{ ...order, status: 'cancelled' }} roomName="Skyline" />); expect(cancelled.getByText('The venue cancelled this order. Refund details will appear here when available.')).toBeTruthy(); expect(cancelled.queryByText(/payment rail|venue relay/i)).toBeNull(); });
  it('routes urgency-ranked Me rows without exposing internal or relay language', () => { const wallet = jest.fn(); const tickets = jest.fn(); const view = render(<MeScreen activeOrder={order} hasMembership ticketCount={1} onMemberships={jest.fn()} onOrders={jest.fn()} onProfile={jest.fn()} onTickets={tickets} onWallet={wallet} roomName="Skyline" />); expect(view.getByText('Ready for pickup')).toBeTruthy(); expect(view.getByText('1 saved ticket')).toBeTruthy(); expect(view.queryByText(order.orderRef, { exact: false })).toBeNull(); expect(view.queryByText(/relay-confirmed/i)).toBeNull(); fireEvent.press(view.getByTestId('me-wallet')); fireEvent.press(view.getByTestId('me-tickets')); expect(wallet).toHaveBeenCalled(); expect(tickets).toHaveBeenCalled(); });
  it('keeps membership purchase disabled without payment rails', () => { const view = render(<MembershipOfferScreen membership={membership} onBack={jest.fn()} onPaymentMethods={jest.fn()} roomName="Skyline" />); expect(view.getByTestId('membership-purchase-disabled').props.accessibilityState.disabled).toBe(true); });
  it('shows explicit active membership and a presentation surface', () => { const view = render(<MembershipDetailScreen entitlement={entitlement} membership={membership} onBack={jest.fn()} roomName="Skyline" />); expect(view.getByText('Active')).toBeTruthy(); expect(view.getByText('Present membership')).toBeTruthy(); });
  it('groups durable access and opens the exact award', () => { const open = jest.fn(); const pass = { ...entitlement, awardId: 'f'.repeat(64), type: 'pass' as const, name: 'Three visits', state: 'available' as const, maxUses: 3, remainingUses: 2 }; const view = render(<MembershipsScreen entitlements={[entitlement, pass]} onBack={jest.fn()} onOpen={open} />); expect(view.getByText(/2 uses left/)).toBeTruthy(); fireEvent.press(view.getByTestId(`entitlement-row-${pass.awardId}`)); expect(open).toHaveBeenCalledWith(pass); });
  it('publishes only through the RSVP action for a free event', () => { const rsvp = jest.fn(); const view = render(<EventScreen event={event} going={false} loading={false} onBack={jest.fn()} onRsvp={rsvp} roomName="Skyline" />); fireEvent.press(view.getByTestId('event-rsvp')); expect(rsvp).toHaveBeenCalled(); });
  it('renders an explicit unavailable state instead of substituting another event', () => { const back = jest.fn(); const view = render(<EventScreen going={false} loading={false} onBack={back} onRsvp={jest.fn()} roomName="Skyline" />); expect(view.getByText('Event unavailable')).toBeTruthy(); expect(view.queryByTestId('event-rsvp')).toBeNull(); fireEvent.press(view.getByText('Back')); expect(back).toHaveBeenCalled(); });
  it('does not fabricate wallet money or funding', () => { const wallet = render(<WalletScreen onAddFunds={jest.fn()} onBack={jest.fn()} />); expect(wallet.getByText('Unavailable')).toBeTruthy(); wallet.unmount(); const funds = render(<AddFundsScreen onBack={jest.fn()} />); expect(funds.getByTestId('add-funds-disabled').props.accessibilityState.disabled).toBe(true); });
});
