import { fireEvent, render } from '@testing-library/react-native'; import { ConversationScreen, MessagesScreen } from '@/screens/messages/MessagesScreens';
const message = { id: 'm', recipientPubkey: 'a'.repeat(64), recipientName: 'Maya', roomId: 'room', roomName: 'Skyline', content: 'Hello', createdAt: 1, state: 'requested' as const, direction: 'incoming' as const, protocol: 'nip04' as const };
const conversationProps = { draft: '', onAccept: jest.fn(), onBack: jest.fn(), onBlock: jest.fn(), onChangeDraft: jest.fn(), onNotNow: jest.fn(), onReply: jest.fn(), onReport: jest.fn(), sending: false };
describe('durable messages', () => {
  it('has an honest empty state', () => { expect(render(<MessagesScreen messages={[]} onOpen={jest.fn()} />).getByText(/No conversations/)).toBeTruthy(); });
  it('opens stored conversation context', () => { const open = jest.fn(); const view = render(<MessagesScreen messages={[message]} onOpen={open} />); fireEvent.press(view.getByTestId(`message-row-${message.recipientPubkey}`)); expect(open).toHaveBeenCalledWith(message); });
  it('exposes accept, block, and report controls', () => { const accept = jest.fn(); const block = jest.fn(); const report = jest.fn(); const view = render(<ConversationScreen {...conversationProps} message={message} onAccept={accept} onBlock={block} onReport={report} />); fireEvent.press(view.getByTestId('conversation-accept')); fireEvent.press(view.getByTestId('conversation-block')); fireEvent.press(view.getByTestId('conversation-report')); expect(accept).toHaveBeenCalled(); expect(block).toHaveBeenCalled(); expect(report).toHaveBeenCalled(); });
  it('lets a recipient dismiss a request without publishing a reason', () => { const onNotNow = jest.fn(); const view = render(<ConversationScreen {...conversationProps} message={message} onNotNow={onNotNow} />); fireEvent.press(view.getByTestId('conversation-not-now')); expect(onNotNow).toHaveBeenCalledTimes(1); });
  it('allows a reply only after acceptance', () => { const onChangeDraft = jest.fn(); const onReply = jest.fn(); const accepted = { ...message, state: 'accepted' as const }; const view = render(<ConversationScreen {...conversationProps} draft="See you there" message={accepted} onChangeDraft={onChangeDraft} onReply={onReply} />); fireEvent.changeText(view.getByTestId('conversation-reply-input'), 'Later'); fireEvent.press(view.getByTestId('conversation-send-reply')); expect(onChangeDraft).toHaveBeenCalledWith('Later'); expect(onReply).toHaveBeenCalled(); });
});
