import { fireEvent, render } from '@testing-library/react-native';
import { InviteAcceptedScreen } from '@/screens/onboarding/InviteAcceptedScreen';
import { InvitePreviewScreen } from '@/screens/onboarding/InvitePreviewScreen';
import { LoginScreen } from '@/screens/onboarding/LoginScreen';
import type { RoomDescriptor } from '@/rooms/types';

const preview = { claims: { v: 1 as const, nonce: 'n', badge: `30009:${'a'.repeat(64)}:members`, exp: 2_000_000_000, max: 1 }, community: { community_root: 'a'.repeat(64), admins: ['a'.repeat(64)], badge_issuer: 'c'.repeat(64), relay_url: 'wss://venue.test', required_badge: `30009:${'a'.repeat(64)}:members` }, serviceUrl: 'https://venue.test' };
const room: RoomDescriptor = { id: 'room', address: `30312:${'a'.repeat(64)}:room`, communityAddress: `31727:${'b'.repeat(64)}:community`, rootPubkey: 'b'.repeat(64), name: 'The Skyline Room', about: 'Rooftop jazz', relayUrl: 'wss://venue.test', operatorPubkey: 'a'.repeat(64), serviceUrl: 'https://venue.test', capabilities: ['membership'], status: 'open', open: true, verified: true };

describe('invite and login screens', () => {
  it('shows the verified room, grant, and expiry before asking for an account', () => { const create = jest.fn(); const view = render(<InvitePreviewScreen hasIdentity={false} loading={false} onAccept={jest.fn()} onBack={jest.fn()} onCreateAccount={create} onLogIn={jest.fn()} preview={preview} redeeming={false} room={room} />); expect(view.getByRole('header', { name: 'A room is waiting for you' })).toBeTruthy(); expect(view.getByText('You’re invited!')).toBeTruthy(); expect(view.getAllByText('The Skyline Room')).toHaveLength(2); expect(view.getByText('Rooftop jazz')).toBeTruthy(); expect(view.getByText('Expires')).toBeTruthy(); expect(view.getByText('Room membership')).toBeTruthy(); expect(view.getByText(/Issuer details match this invitation/)).toBeTruthy(); expect(view.getByText(/never makes you visible/i)).toBeTruthy(); fireEvent.press(view.getByTestId('invite-accept-button')); expect(create).toHaveBeenCalled(); });
  it('allows an existing identity to accept', () => { const accept = jest.fn(); const view = render(<InvitePreviewScreen hasIdentity loading={false} onAccept={accept} onBack={jest.fn()} onCreateAccount={jest.fn()} onLogIn={jest.fn()} preview={preview} redeeming={false} room={null} />); fireEvent.press(view.getByTestId('invite-accept-button')); expect(accept).toHaveBeenCalled(); });
  it('keeps room entry explicit after success', () => { const join = jest.fn(); const membership = jest.fn(); const view = render(<InviteAcceptedScreen eventId={'b'.repeat(64)} onJoinRoom={join} onMembership={membership} roomName="Skyline" />); expect(view.getByText('You’re on the list.')).toBeTruthy(); expect(view.getByText('Room membership')).toBeTruthy(); expect(view.getByText(`Signed award · ${'b'.repeat(12)}…`)).toBeTruthy(); expect(view.getByText(/not visible/i)).toBeTruthy(); fireEvent.press(view.getByTestId('invite-view-membership')); expect(membership).toHaveBeenCalled(); fireEvent.press(view.getByTestId('invite-join-room')); expect(join).toHaveBeenCalled(); });
  it('offers local unlock with honest Nostr custody and preserved invite truth', () => { const unlock = jest.fn(); const view = render(<LoginScreen hasDeviceIdentity loading={false} onBack={jest.fn()} onCreateAccount={jest.fn()} onRecovery={jest.fn()} onUnlock={unlock} preservingInvite />); expect(view.getByText(/Your invitation is saved while you unlock this account/)).toBeTruthy(); expect(view.getByText('No Crays password')).toBeTruthy(); expect(view.queryByText('Continue with Apple')).toBeNull(); expect(view.queryByText('Continue with Google')).toBeNull(); fireEvent.press(view.getByTestId('login-device-unlock')); expect(unlock).toHaveBeenCalled(); });
  it('routes a new-device login into the existing Nostr identity workflow', () => { const existing = jest.fn(); const view = render(<LoginScreen hasDeviceIdentity={false} loading={false} onBack={jest.fn()} onCreateAccount={jest.fn()} onRecovery={existing} onUnlock={jest.fn()} preservingInvite={false} />); expect(view.getByRole('header', { name: 'Log in with Nostr' })).toBeTruthy(); expect(view.getByText(/Connect a signer app/)).toBeTruthy(); fireEvent.press(view.getByTestId('login-existing-identity')); expect(existing).toHaveBeenCalledTimes(1); });
});
